# Generated by Django 4.1.4 on 2022-12-18 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sizes_size_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100, null=True)),
                ('postal_code', models.CharField(max_length=15, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('unique_code', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('gross_amount', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.AutoField(primary_key=True, serialize=False)),
                ('province_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('courier', models.CharField(max_length=100, null=True)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cities')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPurchases',
            fields=[
                ('product_purchases_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier', models.CharField(max_length=150)),
                ('stock', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.BooleanField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('store', models.CharField(max_length=100)),
                ('gross_amount', models.IntegerField()),
                ('payment_type', models.CharField(max_length=100)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order')),
            ],
        ),
        migrations.AddField(
            model_name='cities',
            name='province_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.province'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('unique_code', models.CharField(max_length=250)),
                ('status', models.BooleanField()),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('price_total', models.FloatField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
