# Generated by Django 4.1.4 on 2022-12-18 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cities_order_province_shipment_productpurchases_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpurchases',
            options={'verbose_name_plural': 'Product Purchases'},
        ),
    ]
