# Generated by Django 4.1.4 on 2022-12-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_order_date_order_product_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='unique_code',
        ),
    ]
