# Generated by Django 4.1.4 on 2022-12-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_cart_status_remove_cart_unique_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='store',
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
