# Generated by Django 4.1.4 on 2022-12-29 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_order_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundProduct',
            fields=[
                ('refund_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=250)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
