# Generated by Django 4.1.4 on 2023-01-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='type',
        ),
    ]
