# Generated by Django 4.1.4 on 2022-12-29 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_refundproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='refundproduct',
            name='user',
        ),
        migrations.AddField(
            model_name='refundproduct',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.order'),
        ),
    ]
