# Generated by Django 4.1.4 on 2023-01-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_cities_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
