# Generated by Django 4.1.4 on 2023-01-02 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_cities_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='product_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.order'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.cities'),
        ),
    ]
