# Generated by Django 4.1.4 on 2022-12-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_refundproduct_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundproduct',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
