# Generated by Django 4.1.4 on 2023-01-02 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_refundproduct_price'),
        ('home', '0016_shipment_product_order_alter_shipment_city'),
    ]

    operations = [
    ]
