# Generated by Django 4.1.4 on 2023-01-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_cities_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='etd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
