# Generated by Django 4.1.4 on 2023-01-08 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_shipment_cost_shipment_description_shipment_etd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='courier',
        ),
    ]
