# Generated by Django 4.1.5 on 2023-02-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_order_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name_plural': 'Entry Brands'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Transaction Carts'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Entry Categories'},
        ),
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name_plural': 'Transaction Cities'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Transaction Orders'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Transaction Payments'},
        ),
        migrations.AlterModelOptions(
            name='productpurchases',
            options={'verbose_name_plural': 'Trans Product Purchases'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Entry Products'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name_plural': 'Transaction Provinces'},
        ),
        migrations.AlterModelOptions(
            name='refundproduct',
            options={'verbose_name_plural': 'Trans Refund Product'},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'verbose_name_plural': 'Transaction Shipments'},
        ),
        migrations.AlterModelOptions(
            name='sizecategories',
            options={'verbose_name_plural': 'Entry Size Categories'},
        ),
        migrations.AlterModelOptions(
            name='sizes',
            options={'verbose_name_plural': 'Entry Sizes'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
    ]
