# Generated by Django 4.1.5 on 2023-02-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_brands_options_alter_cart_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Cities',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
